### PR TITLE
Add support for Unicode 15.1

### LINKED ISSUE #60: Update for Unicode 15.1
With the [release of Unicode 15.1](http://blog.unicode.org/2023/09/announcing-unicode-standard-version-151.html), it's time for another update to `unicodedata2`.

Aside from bumping `UNIDATA_VERSION`, the new CJK Ideograph Extension I needs to be added to the unified CJK ranges, and there's also a bug in `makeunicodedata.py` based on how it handles character properties. This may also a good opportunity to review the changes from #58, and to add Python 3.12 (scheduled to come out on 2 October 2023) to the library's `tox` configuration.

I have opened [an upstream PR](https://github.com/python/cpython/pull/109560) since this involves a bugfix in the CPython tooling, I figure I won't open a PR for `unicodedata2` until this is merged to minimize drift from the upstream, but I can say that applying the same changeset to the relevant files in `unicodedata2` does work and the test suite passes.

EDIT: the upstream PR has landed, PR forthcoming.

### PR DESCRIPTION
**Pull request by SnoopJ**
This changeset updates `unicodedata2` to add Unicode 15.1 support, following the analogous changes [upstream](https://github.com/python/cpython/issues/109559). There are also some housekeeping changes: synchronizing the test suite and dropping dead code that used to support narrow builds of CPython. The overall result of this housekeeping is that the expectation checksum now follows the value in the upstream test suite.

This changeset also adds Python 3.12 to the `tox` configuration in anticipation of the coming release.

Closes #60, #61

### CODE REVIEW

**Review by anthrotype — APPROVED** [review]
Thank you! LGTM

**Comment by jbicha** [comment]
@anthrotype Could you tag a new release?

**Comment by anthrotype** [comment]
Yes, I will do tomorrow, thanks for the reminder. @SnoopJ is there anything else you'd like to get in before the next release?

**Comment by SnoopJ** [comment]
> @SnoopJ is there anything else you'd like to get in before the next release?

Nope! The only thing currently on my radar is follow-on from #56 now that 3.7 is EOL, but it isn't necessary for a 15.1 release and I haven't thought about it very much :sweat_smile:

**Comment by anthrotype** [comment]
Done! https://pypi.org/project/unicodedata2/15.1.0/#files

**Pull request merged**
