### PR TITLE
Port several things from cpython here

### LINKED ISSUE #25: Add is_normalize (port upstream)
There are a few commits at https://github.com/python/cpython/commits/master/Modules/unicodedata.c that aren’t in our versions. We should port/backport them.

### PR DESCRIPTION
**Pull request by mikekap**
Closes #25 

 - Fix bugs for in hangul composition check boundaries (https://github.com/python/cpython/commit/d134809cd3764c6a634eab7bb8995e3e2eff14d5)
 - Copy the normalization test so it runs for us too
 - Implement `is_normalized`

### CODE REVIEW

**Comment by anthrotype** [comment]
Thanks for this!

About the Travis CI failure, it seems like the current multibuild no longer supports python3.5. Since it has reached EOL for a while, I would suggest to remove it from the CI build matrix.

**Comment by anthrotype** [comment]
what's the status of this?

**Comment by anthrotype** [comment]
closing as superseded by #58

**Comment by SnoopJ** [comment]
@anthrotype I think #25 can be closed as well since this issue is marked as closing that one and it isn't clear which exact commits were being referred to

**Comment by anthrotype** [comment]
but did your PR impelement `is_normalized`? If not maybe we should keep #25 open

**Comment by SnoopJ** [comment]
> but did your PR impelement `is_normalized`? If not maybe we should keep #25 open

Hmm I guess I read the issue too quickly earlier. #58 does port some changes to the C-side `is_normalize` machinery, but it does not add `is_normalize()` to the Python-facing API.

#25 is still a valid need for `unicodedata2` to have parity with upstream. Sorry about the noise! :grimacing:

**Pull request closed without merging**
