### PR TITLE
Update to Unicode 14.0

### PR DESCRIPTION
**Pull request by khaledhosny**

### CODE REVIEW

**Comment by khaledhosny** [comment]
It looks like the TravisCI setup is no longer functional.

**Comment by khaledhosny** [comment]
> It looks like the TravisCI setup is no longer operational.

Nor AppVeyor.

**Comment by anthrotype** [comment]
Thanks Khaled, just checking -- how did you go about updating the unicodedata database? Since this is done so infrequently, I always forget how this was done the year before. Maybe we can/should add a note to the README as reminder for future selves.

**Comment by khaledhosny** [comment]
I changed the Unicode version in the `makeunicodedata.py` script and ran it, it downloaded the data and regenerated the database. It complained about the CJK rangés not matching the ones in the script, so I updated them to match (no idea why the script does not do that itself). The change in the C files is copied from the cpython commit referenced in #44.

**Review by anthrotype — APPROVED** [review]

**Comment by anthrotype** [comment]
@khaledhosny sounds good to me

@Harmon758 will this mark #44 as completed?

**Comment by anthrotype** [comment]
@khaledhosny can to merge or rebase origin/master to run the GitHub Actions checks?

**Pull request merged**
